# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-20 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20171120_1836'),
        ('quotes_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='owner',
        ),
        migrations.AddField(
            model_name='quote',
            name='favorite',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='login_app.User'),
            preserve_default=False,
        ),
    ]
