# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-20 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20171120_1836'),
        ('quotes_app', '0002_auto_20171120_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='owner',
            field=models.ManyToManyField(related_name='owners', to='login_app.User'),
        ),
    ]
